/**
 * Seed data pulled from the live TenderEngine Notion workspace on 2026-04-21
 * via MCP. This is a real snapshot of the current tender portfolio — not
 * fabricated demo data. When NOTION_TOKEN is set in .env.local, the
 * /api/tenders route bypasses this seed and queries Notion directly.
 */

import type {
  AgentRun,
  Client,
  CurrentDraft,
  FeedEvent,
  Section,
  Tender,
} from "./types";

export const SEED_TENDERS: Tender[] = [
  {
    id: "3445f845-fa2b-8198-aaf4-eca677ebafb4",
    reference: "T26/10",
    name: "T26/10 — Property Management Services",
    clientId: "3485f845-fa2b-8160-8015-eb54edfe3b3b",
    clientName: "Belroy Property",
    deadline: "2026-04-23",
    decisionDate: null,
    status: "Drafting",
    priority: "Urgent",
    result: null,
    submissionMethod: "Portal",
    owner: null,
    outputDoc: "https://docs.google.com/document/d/1gGz0oRlNvntPjZc1ypA5_kCIZiFuf0v9/edit",
    tenderDocs: "https://drive.google.com/drive/u/0/folders/1EHkHNvarLDq-0IEATQViTqKmI-Spy2FF",
    sectionsFound: 21,
    sectionsMapped: 21,
    sectionsDrafted: 4,
    gapsFound: 13,
    blockers: "",
    complianceFlags: "",
    estimatedValue: "",
    nextAction:
      "Belroy Property presentation 2026-04-22 — walk through Part 4 DRAFT RESPONSE, collect client-only answers live, re-run drafting after meeting.",
    agentNotes:
      "Buyer: Campbelltown City Council. Property: Homebase Campbelltown LFR, 10,738 sqm GLA, 13 tenancies. ABN 48 137 115 587 CONFIRMED and filled in RF2 + RF19.",
  },
  {
    id: "32b5f845-fa2b-81c5-adaa-c2d1da9259dd",
    reference: "CP028",
    name: "CP028 — Provision of Arboriculture Services (FCRC)",
    clientId: "32b5f845-fa2b-8196-85c9-e98ce14e536a",
    clientName: "Arbor Metro",
    deadline: "2026-03-26",
    decisionDate: "2026-04-23",
    status: "Submitted",
    priority: "Urgent",
    result: "Pending",
    submissionMethod: "Portal",
    owner: "Partner",
    outputDoc: "https://docs.google.com/document/d/1ap-dDaKdu-yOSXZl-WBnP120b39FJWO0FfzA7sF1Cv8/edit",
    tenderDocs: "https://drive.google.com/drive/folders/1yyAlz6w3FSEFP6wgO0p0bk2Kd1iR5leH",
    sectionsFound: 15,
    sectionsMapped: 15,
    sectionsDrafted: 12,
    gapsFound: 17,
    blockers:
      "Fundamental service mismatch: consultancy vs practical tree work. Addendum #1 excludes consultants.",
    complianceFlags: "Addendum #1 excludes arboricultural consultants from this panel.",
    estimatedValue: "",
    nextAction: "Awaiting decision 2026-04-23.",
    agentNotes:
      "Triage 22/03 (no-bid recommended, service mismatch). Drafted 24/03 per client instruction.",
  },
  {
    id: "33f5f845-fa2b-8195-8ae0-e39920374a0b",
    reference: "Q26-0164",
    name: "Q26-0164 — Comprehensive Valuation for Investment Property Portfolio",
    clientId: "33f5f845-fa2b-8104-ab1a-cc5709effcc9",
    clientName: "Sun Valuation",
    deadline: "2026-04-14",
    decisionDate: "2026-04-24",
    status: "Submitted",
    priority: "Normal",
    result: "Pending",
    submissionMethod: "Email",
    owner: "H",
    outputDoc: "https://docs.google.com/document/d/18g3_H5DO7uZGkRKUHyynxatbmlLdQVr8/edit",
    tenderDocs: "https://drive.google.com/drive/u/0/folders/10rZMowY30k5FgPzLyLUEBqpUsyb-aT1A",
    sectionsFound: 14,
    sectionsMapped: 14,
    sectionsDrafted: 14,
    gapsFound: 18,
    blockers: "",
    complianceFlags: "",
    estimatedValue: "",
    nextAction: "Awaiting decision 2026-04-24.",
    agentNotes:
      "Client: Sun Valuation (Emily Shade). Draft Pricing subtotal $98,200 ex-GST across 16 of 17 properties.",
  },
  {
    id: "3365f845-fa2b-8145-ab16-ec8bdeb335fa",
    reference: "WS5488828273",
    name: "WS5488828273 — TfNSW Physiotherapy Services",
    clientId: "31b5f845-fa2b-80fa-a9b7-e59641a0199d",
    clientName: "A & S Allied Health",
    deadline: "2026-04-10",
    decisionDate: "2026-06-01",
    status: "Submitted",
    priority: "High",
    result: null,
    submissionMethod: "Portal",
    owner: "H",
    outputDoc: "https://docs.google.com/document/d/1fyUrtFlSR1H6bJv3EAm798sh1-BAlDfSmlQyKATaRFI/edit",
    tenderDocs: "https://drive.google.com/drive/folders/1U2cvICxwcak4O3WuMANqqHl-qwo1Kbvo",
    sectionsFound: 10,
    sectionsMapped: 10,
    sectionsDrafted: 7,
    gapsFound: 8,
    blockers: "",
    complianceFlags: "Motor vehicle insurance ($20M) unknown. Financial statements not on file.",
    estimatedValue: "$1.41M/yr. 7-yr profit $5.7M.",
    nextAction: "Awaiting evaluation ~1 June 2026.",
    agentNotes:
      "Submitted 10 April 2026 via Ariba. Per-session reporting and no cancellation fees as USPs.",
  },
  {
    id: "3185f845-fa2b-80ae-a15a-e2c190a3c4b8",
    reference: "21109",
    name: "Contract 21109 — Croydon Community Hub & Library Cleaning",
    clientId: "3185f845-fa2b-809d-80a6-d43c03ac60dc",
    clientName: "Extreme Cleaning & Maintenance Services",
    deadline: "2026-04-15",
    decisionDate: null,
    status: "Submitted",
    priority: "High",
    result: null,
    submissionMethod: "Portal",
    owner: "H",
    outputDoc: "https://docs.google.com/document/d/1KP2HdJeyB7lzyi457-qg1_kQbtH-ZeEgpUdouYPOlcg/edit",
    tenderDocs: "https://drive.google.com/drive/folders/1NIPvDQg3RL2IsVW_8SN_4SLLd8TngTw5",
    sectionsFound: 12,
    sectionsMapped: 12,
    sectionsDrafted: 12,
    gapsFound: 4,
    blockers: "",
    complianceFlags: "WWC Checks for all staff — client must confirm and provide evidence register.",
    estimatedValue: "",
    nextAction: "",
    agentNotes: "",
  },
  {
    id: "31d5f845-fa2b-8036-bf5d-e41c7c6d8cf1",
    reference: "SWSPHN-1155237",
    name: "SWSPHN Falls Prevention — Stepping On Program",
    clientId: "31b5f845-fa2b-80fa-a9b7-e59641a0199d",
    clientName: "A & S Allied Health",
    deadline: "2026-04-13",
    decisionDate: null,
    status: "Submitted",
    priority: "High",
    result: "Pending",
    submissionMethod: "Portal",
    owner: null,
    outputDoc: "https://docs.google.com/document/d/1RJQOyzaZHOGHs6iWD0msAPR7CLtGsMcwS2EYJjbInmI/edit",
    tenderDocs: "https://drive.google.com/drive/u/0/folders/1EGbbIMCKrHwIMLFYxkAW9p_7ZtoIS-14",
    sectionsFound: 10,
    sectionsMapped: 10,
    sectionsDrafted: 4,
    gapsFound: 12,
    blockers: "",
    complianceFlags:
      "Cyber security $1M insurance and audited financial statements outstanding at submission.",
    estimatedValue: "$622,882 ex GST",
    nextAction: "",
    agentNotes: "Q1–Q3 into Tenderlink portal. Q4 Work Plan filled. Q5 budget completed.",
  },
  {
    id: "33f5f845-fa2b-8154-b7d4-ce9881b2621b",
    reference: "2026-5",
    name: "2026-5 — WhittleSea Council Arborist Services",
    clientId: "32b5f845-fa2b-8196-85c9-e98ce14e536a",
    clientName: "Arbor Metro",
    deadline: "2026-04-14",
    decisionDate: null,
    status: "Submitted",
    priority: "Urgent",
    result: "Pending",
    submissionMethod: "Portal",
    owner: "H",
    outputDoc: "https://docs.google.com/document/d/1cO1dXnEh1sVPaktI2ZDHv7ls1KEzWmB_pWn00XRBGqY/edit",
    tenderDocs: "https://drive.google.com/drive/folders/1riC89O9GNhBUPj8-qVH4PD7gIM1sLhnB",
    sectionsFound: 28,
    sectionsMapped: 28,
    sectionsDrafted: 22,
    gapsFound: 7,
    blockers: "",
    complianceFlags:
      "PI insurance $5M held vs $20M required. Motor $20M missing. Modern slavery policy required.",
    estimatedValue: "",
    nextAction: "",
    agentNotes: "Bid Portion A only. Arbor Metro is a consultancy — practical crew work excluded.",
  },
  {
    id: "3255f845-fa2b-80f9-b6d2-e02f045d2c69",
    reference: "2526-010",
    name: "2526-010 — Arboricultural Planning Advisory Services",
    clientId: "32b5f845-fa2b-8196-85c9-e98ce14e536a",
    clientName: "Arbor Metro",
    deadline: "2026-03-26",
    decisionDate: "2026-05-25",
    status: "Submitted",
    priority: "Urgent",
    result: null,
    submissionMethod: "Portal",
    owner: "Partner",
    outputDoc: "https://docs.google.com/document/d/1JmnAWbaLDQdizdlTFWjJHyBL0D89E3-ryXFl1zbzfZg/edit",
    tenderDocs: "https://drive.google.com/drive/u/0/folders/1UwKDI8wbM8P3_7B0FSG2xK_3OAVYPfEt",
    sectionsFound: 18,
    sectionsMapped: 18,
    sectionsDrafted: 14,
    gapsFound: 15,
    blockers: "",
    complianceFlags: "PL $20M, PI $5M, WorkCover, Motor Vehicle required. WWC card mandatory.",
    estimatedValue: "",
    nextAction: "Awaiting decision 2026-05-25.",
    agentNotes: "Advisory/consulting role matches Arbor Metro's core business.",
  },
  {
    id: "3355f845-fa2b-8068-974d-d75afdc4074e",
    reference: "SCHN_2411225",
    name: "Retail Expansion Project — Westmead EOI",
    clientId: "3175f845-fa2b-8146-8b57-d041834d1ebd",
    clientName: "Arista Coffee",
    deadline: "2026-04-14",
    decisionDate: null,
    status: "Submitted",
    priority: "Normal",
    result: null,
    submissionMethod: "Portal",
    owner: null,
    outputDoc: "https://docs.google.com/document/d/1iFxXZAR8MroaT0U7voHNekYYQmZGqlAa/edit",
    tenderDocs: "https://drive.google.com/drive/folders/1Rd47NNlrXMYsPOOwEzIpZOSyRzmb7Qbw",
    sectionsFound: 9,
    sectionsMapped: 9,
    sectionsDrafted: 9,
    gapsFound: 7,
    blockers: "",
    complianceFlags:
      "Strategic fit warning: EOI seeks experienced retail operators. Arista is wholesale supplier.",
    estimatedValue: "Retail lease (rent payable by tenant)",
    nextAction: "Stage 2 decision ~May 2026.",
    agentNotes:
      "Operating model: Arista (supply) + external cafe operator (Arthur). Shortlisting is Stage 1.",
  },
  {
    id: "31f5f845-fa2b-80ef-8ecc-c5aba854f529",
    reference: "25DTS018B-PHY",
    name: "QAS Performance Physiotherapy — Sunshine Coast",
    clientId: "31b5f845-fa2b-80fa-a9b7-e59641a0199d",
    clientName: "A & S Allied Health",
    deadline: "2026-03-25",
    decisionDate: "2026-04-30",
    status: "Not Doing",
    priority: "High",
    result: "Pending",
    submissionMethod: "Portal",
    owner: "H",
    outputDoc: null,
    tenderDocs: null,
    sectionsFound: 20,
    sectionsMapped: 20,
    sectionsDrafted: 0,
    gapsFound: 10,
    blockers:
      "No specific named physiotherapist confirmed. Workers comp cert not on file. PI shortfall $10M vs $20M.",
    complianceFlags: "Practitioner contract — named AHPRA physio with 2+ yrs elite athlete experience required.",
    estimatedValue: "$48,720–$61,440 initial term; up to $184,320 over 3 years",
    nextAction: "Recruitment decision required.",
    agentNotes: "No-bid recommended pending practitioner recruitment decision.",
  },
];

export const SEED_CLIENTS: Client[] = [
  {
    id: "3485f845-fa2b-8160-8015-eb54edfe3b3b",
    companyName: "Belroy Property",
    tradingName: null,
    abn: "48 137 115 587",
    acn: null,
    contactName: "Peter Karam",
    contactEmail: null,
    contactPhone: null,
    driveFolder: "https://drive.google.com/drive/folders/1BzKnWvZ3g7USWArtRbP0mBBIjH1I1dkW",
    profileStatus: "In Progress",
    sectors: ["Facilities", "Other"],
    itemsMissing: 7,
    docsReviewed: 2,
  },
  {
    id: "32b5f845-fa2b-8196-85c9-e98ce14e536a",
    companyName: "Arbor Metro Pty Ltd",
    tradingName: "Arbor Metro",
    abn: "76 694 241 846",
    acn: "694 241 846",
    contactName: "Stefanos Diakanastasis",
    contactEmail: "stefanos@arbormetro.com.au",
    contactPhone: "0423 285 899",
    driveFolder: null,
    profileStatus: "In Progress",
    sectors: ["Other"],
    itemsMissing: 3,
    docsReviewed: 6,
  },
  {
    id: "31b5f845-fa2b-80fa-a9b7-e59641a0199d",
    companyName: "A & S Allied Health",
    tradingName: null,
    abn: "55 683 156 470",
    acn: "683 156 470",
    contactName: "Alisha Arora",
    contactEmail: "admin@asalliedhealth.com.au",
    contactPhone: null,
    driveFolder: "https://drive.google.com/drive/folders/1focfGx2Gac6j2QmsdwaLm22jB0gLGgic",
    profileStatus: "In Progress",
    sectors: ["Allied Health"],
    itemsMissing: 5,
    docsReviewed: 12,
  },
  {
    id: "3175f845-fa2b-8146-8b57-d041834d1ebd",
    companyName: "Arista Coffee",
    tradingName: null,
    abn: "66 634 940 891",
    acn: null,
    contactName: "Spiro",
    contactEmail: null,
    contactPhone: null,
    driveFolder: "https://drive.google.com/drive/folders/1t7AfFtJbrdLfof1aY7cNlPEDtM4krokT",
    profileStatus: "In Progress",
    sectors: ["Coffee", "Food & Beverage"],
    itemsMissing: 4,
    docsReviewed: 8,
  },
  {
    id: "3185f845-fa2b-809d-80a6-d43c03ac60dc",
    companyName: "Extreme Cleaning & Maintenance Services",
    tradingName: "ECMS",
    abn: null,
    acn: null,
    contactName: null,
    contactEmail: null,
    contactPhone: null,
    driveFolder: null,
    profileStatus: "In Progress",
    sectors: ["Cleaning"],
    itemsMissing: 4,
    docsReviewed: 3,
  },
  {
    id: "33f5f845-fa2b-8104-ab1a-cc5709effcc9",
    companyName: "Sun Valuation",
    tradingName: "Sun Valuation",
    abn: null,
    acn: null,
    contactName: "Emily Shade",
    contactEmail: null,
    contactPhone: null,
    driveFolder: null,
    profileStatus: "Incomplete",
    sectors: ["Other"],
    itemsMissing: 6,
    docsReviewed: 0,
  },
];

// ─── Per-active-tender runtime placeholders ────────────────────────────
// These are starting values for the active tender. The agent cards, sections,
// feed, and draft pane are not rendered in this pass, but the shapes are here
// for when they're wired.

export const SEED_AGENTS: AgentRun[] = [
  {
    id: "onboarding",
    label: "01",
    name: "Onboarding",
    role: "Audits client Drive folder + Notion profile. Scores readiness.",
    state: "done",
    startedAt: "2026-04-21T06:12:00+10:00",
    finishedAt: "2026-04-21T06:21:00+10:00",
    duration: "9m 04s",
    output: "Readiness 62/100 · 7 shopping-list items",
  },
  {
    id: "triage",
    label: "02",
    name: "Triage",
    role: "Maps sections, detects format, flags pass/fail items, lists gaps.",
    state: "done",
    startedAt: "2026-04-21T07:02:00+10:00",
    finishedAt: "2026-04-21T07:14:00+10:00",
    duration: "12m 41s",
    output: "21 sections · 4 pass/fail · 13 gaps · Word template detected",
  },
  {
    id: "drafting",
    label: "03",
    name: "Drafting",
    role: "Writes directly into the RFT response document.",
    state: "running",
    startedAt: "2026-04-21T14:03:00+10:00",
    finishedAt: null,
    duration: "18m 41s",
    output: "RF6 · Delivery Approach & Methodology",
    progress: 0.62,
  },
  {
    id: "polish",
    label: "04",
    name: "Polish",
    role: "Removes AI writing patterns. Em dashes, filler, banned phrases.",
    state: "queued",
    startedAt: null,
    finishedAt: null,
    duration: null,
    output: null,
  },
  {
    id: "debrief",
    label: "05",
    name: "Debrief",
    role: "Post-submission. Captures result, enriches client profile.",
    state: "idle",
    startedAt: null,
    finishedAt: null,
    duration: null,
    output: null,
  },
];

export const SEED_SECTIONS: Section[] = [
  { n: "RF1", title: "Form of Tender", state: "done", words: 184 },
  { n: "RF2", title: "Tenderer Information", state: "gap", note: "ABN confirmed; other fields awaited" },
  { n: "RF3", title: "Company Experience & Subcontracting", state: "gap", note: "LFR case studies awaited" },
  { n: "RF4", title: "References", state: "blocker", note: "3 referees required · client data missing" },
  { n: "RF5", title: "Proposed Key Personnel", state: "gap", note: "licences/qualifications awaited" },
  { n: "RF6", title: "Delivery Approach & Methodology", state: "writing" },
  { n: "RF7", title: "Local Consideration", state: "queued" },
  { n: "RF8", title: "Pricing", state: "blocker", note: "client decision" },
  { n: "RF9", title: "Terms of Contract", state: "queued" },
  { n: "RF10", title: "Insurances", state: "blocker", note: "pass/fail · 4 certs awaited" },
];

export const SEED_DRAFT: CurrentDraft = {
  heading: "RF6  Delivery Approach & Methodology",
  question:
    "Describe how the tenderer will implement financial management, lease management, staff resources, FM, marketing, reporting and communication strategy for Homebase Campbelltown.",
  paragraphs: [
    {
      kind: "p",
      spans: [
        { text: "We bring a " },
        { text: "21-year partnership", bold: true },
        {
          text: " in commercial property management across the Parramatta CBD and Western Sydney, with 1,000+ documented transactions and a dedicated team structure that maps directly onto the five management streams in this brief.",
        },
      ],
    },
    {
      kind: "p",
      spans: [
        { text: "Our transition plan covers the " },
        { text: "30 June 2026", bold: true },
        { text: " handover with a week-by-week mobilisation schedule tied to live lease events, including " },
        { text: "Shop 5 (Workscene)", bold: true },
        { text: " expiring August 2026 and " },
        { text: "Shop 10 (Rug Galaxy)", bold: true },
        {
          text: ", currently in holdover. We arrive with a plan for each tenancy, not a generic service pitch.",
        },
      ],
    },
    {
      kind: "p",
      spans: [
        { text: "Reporting cadence to Council: monthly financial pack and tenancy update, quarterly forward leasing plan, and a structured escalation path for any WHS or environmental incidents within " },
        { text: "2 business hours", bold: true },
        { text: ". Professional indemnity cover: " },
        { text: "[AWAITING CLIENT INPUT — PI expiry date (month and year)]", placeholder: true },
        { text: "." },
      ],
    },
    { kind: "writing" },
  ],
};

export const SEED_FEED: FeedEvent[] = [
  { t: "14:21:04", agent: "drafting", level: "info", message: "Writing RF6 Delivery Approach into Output Doc" },
  { t: "14:20:51", agent: "drafting", level: "info", message: "Pulled Belroy 21-year partnership evidence from public profile" },
  { t: "14:20:18", agent: "drafting", level: "warn", message: "RF10 Insurances — 4 certificates of currency awaited. Placeholders inserted." },
  { t: "14:19:02", agent: "drafting", level: "info", message: "Completed RF2 Tenderer Information (ABN 48 137 115 587 confirmed)" },
  { t: "14:15:40", agent: "drafting", level: "info", message: "Completed RF1 Form of Tender (184 words)" },
  { t: "14:14:12", agent: "drafting", level: "info", message: "Drafting agent started · 21 sections in scope" },
  { t: "07:14:02", agent: "triage", level: "done", message: "Triage complete · handoff to Drafting" },
  { t: "07:13:30", agent: "triage", level: "warn", message: "RF4 References — 3 referees required, not in client profile" },
  { t: "07:12:48", agent: "triage", level: "info", message: "Submission format: WORD_TEMPLATE (Part 4 DOCX, 21 response forms)" },
  { t: "07:08:22", agent: "triage", level: "info", message: "Triage agent started · reading RFT Documents/" },
];
